name: ds-viz-plotly
channels:
  - conda-forge
  - defaults
dependencies:
  - ca-certificates
  - openssl
  - certifi
  - ipywidgets
  - nodejs
  - plotly=4.4.1
  - psutil
  - requests
  - dash
  - voila
